### ISSUE TITLE
Preface: Link mistake

### ISSUE THREAD

**Issue by ReubenHill** [object-oriented-python/object-oriented-programming#21]
In the preface
> Who is this book for?
This book is for anyone with mathematical, scientific, or engineering interests who would like to learn to be a more capable programmer. The mathematical examples assume that you know how to differentiate functions of one variable, but very little beyond that. Where examples or exercises employ other mathematics, such as cellular automata in [Chapter 4](https://object-oriented-python.github.io/4_style.html#style) and groups in [Chapter 5](https://object-oriented-python.github.io/5_abstract_data_types.html#abstract-data-types),

You ought to link to chapter 7 on inheritance, which is where groups are first introduced.

**Comment by dham** [comment]
fixed.
