### ISSUE TITLE
Typo/missing phrase in section 4.3.4

### ISSUE THREAD

**Issue by ronniep** [object-oriented-python/object-oriented-programming#3]
The section 4.3.4 contains the sentence: 

> The closing bracket comes on a new line, and is **either** indented to the same level as the first line.

Either the "either" is superfluous or there is another subclause, in which case the example code above it showing permissible options should be updated.

**Comment by dham** [comment]
You're right. An earlier version of the chapter had an other alternative (closing bracket indented the same as the contents). This is allowed under PEP8 (https://www.python.org/dev/peps/pep-0008/#indentation) but Flake8 by default complains about it and I found it confused students.

Thanks for catching this. I've fixed it locally and will put out a fix to the website imminently.
