### ISSUE TITLE
Formatting in Definition 5.3

### ISSUE THREAD

**Issue by ronniep** [object-oriented-python/object-oriented-programming#4]
In the second text line of definition 5.3, i.e.

> if there exists `M>0` and `N>0` such that

 the text "M > 0" and "N > 0" are in different formatting. I don't know if this is intentional or a formatting error.

**Comment by ronniep** [comment]
also f and g in the first line are in bold text but in the mathematical notation afterwards are in math text.

**Comment by dham** [comment]
You are correct! Three times missing `:math:`.
