### ISSUE TITLE
Line numbers appear to be incorrect

### ISSUE THREAD

**Issue by ronniep** [object-oriented-python/object-oriented-programming#6]
In the last paragraphs of 7.1.1 the test runs as follows:

> Listing 7.1 illustrates composition: on **line 4** Element, is associated with a group object. This is a classic has a relationship: an element has a group. We might have attempted to construct this the other way around with classes having elements, however this would have immediately hit the issue that elements have exactly one group, while a group might have an unlimited number of elements. Object composition is typically most successful when the relationship is uniquely defined.
> 
> This code also demonstrates delegation. In order to avoid having to define different element classes for different groups, the element class does not in substance implement either value validation, or the group operation. Instead, at **line 3**, validation is delegated to the group by calling group._validate() and at **line 10** the implementation of the group operation is delegated to the group by calling self.group.operation().

The line numbers all refer to Listing 7.1. but the numbers appear to be wrong (possibly duplicate linking?):

Line 4 should be Line 13
Line 3 should be Line 12
Line 10 should be Line 19

**Comment by dham** [comment]
Argh. I added a doctstring to the function and failed to find these line numbers!
